# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: SKULL AND BONES 
description: A new blog about urban life and music !
baseurl: "" # put subpath of your site, e.g. /blog
url: "" # put the base hostname & protocol for your site

email: 
twitter_username:
github_username:  

paginate: 6

gems: [jekyll-paginate, kramdown]
markdown: kramdown
