# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: LEX BLUMPKIN
description: sudo rm -rf /* and we're done.
baseurl: "/tux" # put subpath of your site, e.g. /blog
url: "https://conspiracyxo.github.io" # put the base hostname & protocol for your site

email: 
twitter_username:
github_username:  

paginate: 6

gems: [jekyll-paginate, kramdown]
markdown: kramdown
